ces_backend/urls.py
from django.contrib import admin
from django.urls import path,include
from user_auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user_auth.urls')),
    path('', views.home,name='home'),
    path('sites/', include(('sites.urls', 'sites'), namespace='sites'))
]

sites/urls.py
from django.urls import path
from sites import views

app_name = 'sites'

urlpatterns = [
    path('sites/', views.getsiteobject, name="get_site_object"),
    path('sites/<int:pk>', views.getdataobject, name="get_data_object")     
]

sites/models.py
from django.db import models
from django.utils import timezone
from enum import Enum
from user_auth.models import User


class Site(models.Model):

    class SiteStatus(Enum):
        Active = 1
        Proposed = 2
        Inactive = 0
        
        @classmethod
        def as_tuple(cls):
            return ((item.value, item.name.replace('_', ' ')) for item in cls)

    name = models.CharField(max_length=1024)
    description = models.TextField(blank=True,null=True)
    status = models.IntegerField(choices=SiteStatus.as_tuple())

    def __str__(self):
        return self.name


class UserSite(models.Model):

    user = models.ForeignKey(User,
                related_name="user_affiliated_site",on_delete=models.CASCADE)
    site = models.ForeignKey(Site,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,blank=True,null=True)
    created_by = models.ForeignKey(User,related_name='user_site_created_user',on_delete=models.DO_NOTHING)
    updated_by = models.ForeignKey(User,blank=True,null=True,related_name='user_site_updated_user',on_delete=models.DO_NOTHING)
    is_valid = models.BooleanField(default=True)


class SiteData(models.Model):
    
    class Name_Type(Enum):  
        Page_View = "PageView"
        Like_Count = "LikeCount"

        @classmethod
        def as_tuple(cls):
            return ((item.value, item.name.replace('_', ' ')) for item in cls)

    user = models.ForeignKey(User,
                related_name="user_site_data",on_delete=models.CASCADE)
    name = models.CharField(max_length=255,choices=Name_Type.as_tuple(),blank=True,null=True)
    site = models.ForeignKey(Site,related_name="site_user",on_delete=models.CASCADE)
    instantaneous_value = models.IntegerField(blank=True,null=True)
    lifetime_value = models.IntegerField(blank=True,null=True)
    eventDate = models.DateTimeField()

sites/views.py
import json
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy,reverse
from user_auth.models import User
from sites.models import UserSite,SiteData,Site


@login_required(login_url="/user/login")
def getsiteobject(request):
    """
        This view is used to get sites object related to particular users depending on developer
        get its object and if examiner gets all the objects of all developer.

    """
    if(request.user.user_type==1):
        active_site= UserSite.objects.filter(site__status=1).distinct('site')
        propsed_site = UserSite.objects.filter(site__status=2).distinct('site')
        inactive_site = UserSite.objects.filter(site__status=0).distinct('site')    
    else:
        active_site = UserSite.objects.filter(user=request.user.id,site__status=1)
        propsed_site = UserSite.objects.filter(user=request.user.id,site__status=2)
        inactive_site = UserSite.objects.filter(user=request.user.id,site__status=0)
    
    context = {
        "active_sites" : active_site,
        "inactive_sites": inactive_site,
        "proposed_sites": propsed_site
    }
    print("Context", context)
    return render(request, 'sites/dashboard.html',context)

@login_required(login_url="/user/login")
def getdataobject(request,pk):

    """ 
    Get data object is used to get data perticular sites related to login user.
    """
    
    page_view_queryset =[]
    like_count_queryset=[]

    if(request.user.user_type==0):
        page_view_queryset = SiteData.objects.filter(name = settings.PAGE_VIEW, user=request.user.id,site=pk).order_by('eventDate')
        like_count_queryset = SiteData.objects.filter(name = settings.LIKE_COUNT, user=request.user.id,site=pk).order_by('eventDate')
    
    elif (request.user.user_type==1):
        page_view_queryset = SiteData.objects.filter(name= settings.PAGE_VIEW,site=pk).order_by('eventDate')
        like_count_queryset = SiteData.objects.filter(name= settings.LIKE_COUNT,site=pk).order_by('eventDate')


    site_info = Site.objects.filter(id=pk)[0]
    page_view_instantaneous_values_list = []
    page_view_eventDate_list = []
    page_view_lifetime_value_list = []

    like_count_instantaneous_values_list = []
    like_count_eventDate_list = []
    like_count_lifetime_value_list = []

    for entry in page_view_queryset:
        page_view_instantaneous_values_list.append(entry.instantaneous_value)
        page_view_eventDate_list.append(entry.eventDate.isoformat())
        page_view_lifetime_value_list.append(entry.lifetime_value)

    for entry in like_count_queryset:
        like_count_instantaneous_values_list.append(entry.instantaneous_value)
        like_count_eventDate_list.append(entry.eventDate.isoformat())
        like_count_lifetime_value_list.append(entry.lifetime_value)

    context = {
        "site_info": site_info,
        "page_view_instantaneous_values_list": json.dumps(page_view_instantaneous_values_list),
        "page_view_event_data_list": json.dumps(page_view_eventDate_list),
        "page_view_lifetime_value_list": json.dumps(page_view_lifetime_value_list),
        "like_count_instantaneous_values_list": json.dumps(like_count_instantaneous_values_list),
        "like_count_event_data_list": json.dumps(like_count_eventDate_list),
        "like_count_lifetime_value_list": json.dumps(like_count_lifetime_value_list)
    }
    return render(request, 'sites/site_detail.html',context)

sites/templates/sites/dashboard.html
{% extends 'user_auth/base.html' %}
{% block head %}
    <style>
        .margin-top{
            margin-top : 30px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
    <div class="row">
    </div>
    <div class="row">
    <div class="col-md-4">
        <div class="dropdown margin-top">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Active Sites
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                {% for site in active_sites %}
                    <li><a href="{%url 'sites:get_data_object' site.site.id %}"> {{ site.site.name }} </a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="col-md-4">
        <div class="dropdown margin-top">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Proposed Sites
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                {% for site in proposed_sites %}
                    <li><a href="{%url 'sites:get_data_object' site.site.id %}"> {{ site.site.name }} </a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="col-md-4">
        <div class="dropdown margin-top">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Inactive Sites
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                {% for site in inactive_sites %}
                    <li><a href="{%url 'sites:get_data_object' site.site.id %}"> {{ site.site.name }} </a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

sites/templates/sites/site_detail.html
{% extends 'user_auth/base.html' %}
{% block head %}
    <script src="https://code.highcharts.com/highcharts.src.js"></script>

{% endblock %}
{% block content %}
<div class="container">
        <div class="row">
            <div class="col-md-6">
                    <div>

                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                              <li role="presentation" class="active"><a href="#pageview" aria-controls="pageview" role="tab" data-toggle="tab">Page Views</a></li>
                              <li role="presentation"><a href="#likecount" aria-controls="likecount" role="tab" data-toggle="tab">Like Count</a></li>
                            </ul>
                            
                            <!-- Tab panes -->
                            <div class="tab-content">
                              <div role="tabpanel" class="tab-pane active" id="pageview">
                                    <div id="chart">

                                    </div>
                                    <div id="inschart">

                                    </div>
            
                              </div>
                              <div role="tabpanel" class="tab-pane" id="likecount">
                                    <div id="likechart">

                                    </div>
                                    <div id="likeinschart">

                                    </div>

                              </div>
                            </div>
                            
                            </div>

            </div>
            <div class="col-md-6">
                <h1>{{ site_info.name }}</h1>
                <p>{{ site_info.description }}</p>
            </div>

        </div>
    </div>

{% endblock %}
{% block footer %}
<script>
    Highcharts.chart('chart', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'page view count (Lifetime value)'
        },
        xAxis: {
            categories: {{  page_view_event_data_list |safe }}
        },
        series: [{
            name: 'Lifetime Value',
            data: {{ page_view_lifetime_value_list }},
            color: 'green'
        }]
    });
  </script>
  <script>
      Highcharts.chart('inschart', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'page view count (Instantaneous value)'
        },
        xAxis: {
            categories: {{  page_view_event_data_list |safe }}
        },
        series: [{
            name: 'Instantaneous Value',
            data: {{ page_view_instantaneous_values_list }},
            color: 'red'
        }]
    });
  </script>

<script>
        Highcharts.chart('likechart', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Like count (Lifetime value)'
            },
            xAxis: {
                categories: {{  like_count_event_data_list |safe }}
            },
            series: [{
                name: 'Lifetime Value',
                data: {{ like_count_lifetime_value_list }},
                color: 'green'
            }]
        });
      </script>
      <script>
          Highcharts.chart('likeinschart', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'like count (Instantaneous value)'
            },
            xAxis: {
                categories: {{  like_count_event_data_list |safe }}
            },
            series: [{
                name: 'Instantaneous Value',
                data: {{ like_count_instantaneous_values_list }},
                color: 'red'
            }]
        });
      </script>



{% endblock %}